var data = [
	{	
		"img":"liuzhiqin.png",
		"desc":"关于此人的描述",
		"name":"刘志勤",
		"title":"教师",
		"content":"刘志勤教授，国家863计划项目评审专家，四川省学术带头人后备人员，绵阳市中青年科技拔尖人才。长期从事现代教育技术、计算机网络应用开发研究，近年来，在《计算机科学》、《计算机应用研究》等核心杂志上公开发表学术论文30余篇，其中多篇被EI检索。先后负责和承担了《基于国产软硬件的多通道网络教育关键技术与应用研究》、《中国西部远程教育基地建设》等国家863计划项目、加拿大国际合作基金项目、省部级等纵、横向科研项目20余项。通过省级鉴定成果2项，获得软件著作权5项。"
	},
	{
		"img":"limaofeng.jpg",
		"desc":"关于此人的描述",
		"name":"黎茂峰",
		"title":"教师",
		"content":"黎茂峰老师，阿伯泰.邓迪大学信息技术工学硕士，中国工程物理研究院无线电物理理学在读博士，西南科技大学计算机科学与技术学院信息媒体系主任。主要研究方向为语义计算、智能计算、网络结构与数字内容管理。"
	},
	{
		"img":"wangqinfeng.png",
		"desc":"关于此人的描述",
		"name":"王庆凤",
		"title":"教师",
		"content":"实验室老师"
	},
	{
		"img":"caidechan.png",
		"desc":"关于此人的描述",
		"name":"蔡德琛",
		"title":"本科生",
		"content":"实验室大二成员"
	},
	{
		"img":"tanglike.jpg",
		"desc":"关于此人的描述",
		"title":"硕士",
		"content":"实验室大二成员",
		"name":"唐礼科"
	},
	{
		"img":"huangjun.png",
		"desc":"关于此人的描述",
		"title":"硕士",
		"content":"实验室研究生",
		"name":"黄俊"
	},
	{
		"img":"wangzhili.jpg",
		"desc":"关于此人的描述",
		"title":"本科生",
		"content":"实验室大二成员",
		"name":"王志利"
	},
	{
		"img":"wuxiaona.jpg",
		"desc":"关于此人的描述",
		"title":"本科生",
		"content":"实验室大二成员",
		"name":"吴晓娜"
	},
	{
		"img":"zhangxiaohua.jpg",
		"desc":"关于此人的描述",
		"title":"本科生",
		"content":"实验室大二成员",
		"name":"张小花"
	},
	{
		"img":"huangjiamei.jpg",
		"desc":"关于此人的描述",
		"title":"本科生",
		"content":"实验室大二成员",		
		"name":"黄嘉美"
	},
	{
		"img":"guangge.jpg",
		"desc":"关于此人的描述",
		"title":"硕士",
		"content":"实验室研究生",
		"name":"光哥"
	},
	{
		"img":"ganzejun.jpg",
		"desc":"关于此人的描述",
		"title":"本科生",
		"name":"甘泽军",
		"content":"实验室大二学生"
	},
]
